### ISSUE TITLE
Node version in Docker image

### ISSUE THREAD

**Issue by javlund** [BulletTrainHQ/bullet-train-frontend#11]
Hi guys, is there a reason you're using the "regular" 300+ MB node Docker image instead of the ~36  MB node alpine image? Otherwise I think that would be a better choice. And perhaps upgrade to node 12 or 13 at the same time.

I'd love to make a PR if you want me to.

**Comment by dabeeeenster** [comment]
Yep there's lots of work to do around Docker optimisation etc on the project - would welcome any PRs! Thanks.

**Comment by javlund** [comment]
That was a swift reply! Here's a pull request: https://github.com/BulletTrainHQ/bullet-train-frontend/pull/12

**Comment by kyle-ssg** [comment]
Closed as this was merged.
