### ISSUE TITLE
Demo app - Problem when trying to disable a feature override for specific user

### ISSUE THREAD

**Issue by wmartins** [BulletTrainHQ/bullet-train-frontend#14]
Hi folks! First of all, thank you for this product! My team is evaluating using Bullet Train as our main feature flagging/rollout tool.

We loved all we saw so far, only one thing we found out was when trying to disable a specific feature flag override, when we click in the toggle option, the feature flag modal just closes.

We tested on the demo app, so, if you want to try it out, here's the link: https://app.bullet-train.io/project/1016/environment/E6Mf24wZHMVwPr5Rqtnh9M/users/879489#

(don't know if it expires).

Also, here goes a gif showing what I mean:

![Gif showing the problem](https://user-images.githubusercontent.com/1560801/75081692-da525580-54ee-11ea-95cc-58e4c4f7cc0a.gif)

In this GIF (in specific user settings screen):

1. Open feature details inside user screen
2. Go to "Identity Overrides" setting
3. Try to click on toggle to disable override
4. The modal just closes

Don't know if it helps, but I've seen the following error on my console:

```
TypeError: e.props.router is undefined CreateFlag.js:270:52
    onClick CreateFlag.js:270
    React 14
    Sn self-hosted:920
    a helpers.ts:77
    (Async: EventListener.handleEvent)
    wrapEventTarget trycatch.ts:123
    React 15
    <anonymous> main.js:64
    a helpers.ts:77
    (Async: setTimeout handler)
    wrapTimeFunction trycatch.ts:32
    <anonymous> main.js:50
    <anonymous> main.js:44
    Webpack 3
```

Thank you!

**Comment by kyle-ssg** [comment]
Hi, @wmartins thanks for the positive feedback! A fix for this is now built on production.

Segment overrides and user overrides were not actually supposed to be visible when editing a users feature states. Editing actually should and should now look like this,  where toggling the feature for that user with is done via the enabled field:

![image](https://user-images.githubusercontent.com/8608314/75089398-41ecbd00-5550-11ea-8826-a50e4a5ec0f3.png)

Identity overrides and segment overrides are only for when managing a feature from an environment i.e. here.

![image](https://user-images.githubusercontent.com/8608314/75089681-6007ec80-5553-11ea-9db3-30d42ffc52df.png)


Thanks for reaching out about this, if there's anything else you have questions about feel free to add another issue.

**Comment by wmartins** [comment]
Hi @kyle-ssg, thanks for the prompt answer! However, I'm still unable to toggle the Identity Overrides, even in Features screen.

In the following example, when I try to click on the Switch element, to disable override for `user-123`, the screen redirects me to `user-123` settings page.

<img width="952" alt="Screen Shot 2020-02-22 at 11 27 39" src="https://user-images.githubusercontent.com/1560801/75094075-6eabcf00-5566-11ea-884e-1507b2492354.png">

To give a little bit more of context, here's what we're trying to achieve:

1. Create a feature (`my/feature`, for example), first as `disabled`
2. Check if `user-123` doesn't has this feature
3. Enable this feature manually to `user-123` (for example, to test something in production)
4. Disable the feature manually to `user-123` (reverting the step 3)
5. Enable `my/feature` to all users

At this point, when evaluating `my/feature` for `user-123`, the feature came as `disabled` (due to step 4). Then, I've tried to disable the override using the UI and then I've come here to open the issue.

If I'm missing something here, let me know. Don't know if this is the expected behavior, as I'm still learning the bits and pieces of Bullet Train.

Thank you!

**Comment by kyle-ssg** [comment]
@wmartins The behaviour you're seeing is intended, it redirects you there because that's where overriding features for a user is possible i.e. by clicking one of the following for a user:

![image](https://user-images.githubusercontent.com/8608314/75095246-cb20e580-558a-11ea-8f16-3b22b5adaf74.png)

**Comment by wmartins** [comment]
Sorry for the confusion @kyle-ssg. I've just seen the big green button saying `Reset` in user features! Thank you for the help!
