### ISSUE TITLE
pipeline for building

### ISSUE THREAD

**Issue by euprogramador** [BulletTrainHQ/bullet-train-frontend#20]
create pipeline for build production and release docker image for distribution

**Comment by euprogramador** [comment]
CicleCi or Github Actions ?

**Comment by dabeeeenster** [comment]
We've set up Docker Hub builds for this. The builds are available here:

https://hub.docker.com/repository/docker/bullettrain/api

https://hub.docker.com/repository/docker/bullettrain/frontend
