### ISSUE TITLE
use docker multistage build for building frontend

### ISSUE THREAD

**Issue by euprogramador** [BulletTrainHQ/bullet-train-frontend#21]
when building the frontend the build process installs npm packages, which comes with the chromium for testing, resulting in a 491 mb image, I suggest using the build process to generate static files and use the nginx or apache image that will be reduced in size and optimized for production use

for that purpose I also suggest using multistage build which would also optimize the build phase.

see: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by dabeeeenster** [comment]
This is now done!
