### ISSUE TITLE
Feature Request: Audit log for a specific feature flag

### ISSUE THREAD

**Issue by nischithbm** [BulletTrainHQ/bullet-train-frontend#26]
Currently, there is audit log capability - which can all logs across feature flags. 
Also, there is a search box, which can help filter audit logs for a specific feature flag.

But, it would be nice to have audit logs accessible against each feature flag, for easy access. This can help debug issues - to see when and who enabled a specific feature flag.

![image](https://user-images.githubusercontent.com/1619263/85332764-2a214780-b4f6-11ea-8a37-dc1a81d2f125.png)

**Comment by kyle-ssg** [comment]
Hey @nischithbm, thanks for logging this. I think your request makes a lot of sense, what I imagine is a link from the features page that links to the audit page with the search box prefilled with the feature name. Would that make sense ?

**Comment by kyle-ssg** [comment]
@nischithbm this is now in production, thank you for the suggestion!

![image](https://user-images.githubusercontent.com/8608314/87245998-16586980-c442-11ea-9b4f-a6f6e592295b.png)
![image](https://user-images.githubusercontent.com/8608314/87246004-21ab9500-c442-11ea-9639-7066de347173.png)
