### ISSUE TITLE
Cannot update a feature

### ISSUE THREAD

**Issue by andrewshawcare** [BulletTrainHQ/bullet-train-frontend#32]
### Steps to reproduce

1. Open a feature for editing
2. Change the description (or any field, potentially)
3. Attempt to update the feature

### Expected behaviour

The feature is updated.

### Actual behaviour

The `POST` request to `/api/v1/projects/{projectId}/features/{featureId}/` results in the following `400` response:

```
{"project":["This field is required."]}
```

**Comment by kyle-ssg** [comment]
Hi @andrewshawcare, we're aware of the issue and it has been fixed in production (https://bullet-train.io). I'll be putting out a new release here on GitHub if you're self hosting.

**Comment by dabeeeenster** [comment]
This is now fixed - thanks for the report!
