### ISSUE TITLE
All features are not listed in the features page

### ISSUE THREAD

**Issue by andrewshawcare** [BulletTrainHQ/bullet-train-frontend#33]
### Steps to reproduce

Create 11 features

### Expected result

11 features should be displayed in the features list

### Actual result

10 features are displayed in the features list

**Comment by kyle-ssg** [comment]
Hi @andrewshawcare I'd be somewhat surprised if this was the case. Can you provide a project perhaps that's experiencing this issue and reopen? 

For reference I've created 11 features on a sample project 

![image](https://user-images.githubusercontent.com/8608314/92132216-cb821f00-edfe-11ea-9780-444641bdd90d.png)

**Comment by andrewshawcare** [comment]
We are using the self-hosted version, I can send some screenshots shortly — thanks!

**Comment by andrewshawcare** [comment]
So the latest version of the docker image for the API seems to paginate with a response to `/api/v1/projects/{projectId}/features` producing:

```
{
   "count":16,
   "next":"https://example.com/api/v1/projects/2/features/?page=2",
   "previous":null,
   "results":[ ... ]
}
```

There is no call to the second page of results and the results array is 10 features, which aligns with the number displayed on the page.

**Comment by andrewshawcare** [comment]
It looks like the call is here: https://github.com/BulletTrainHQ/bullet-train-frontend/blob/46cf709faff7fe0ace68b3f62a469aeb03e88ad8/common/stores/feature-list-store.js#L14

**Comment by andrewshawcare** [comment]
I figured out why. The docker settings does not include the following code from the common settings:

https://github.com/BulletTrainHQ/bullet-train-api/blob/master/src/app/settings/master.py#L40

I created a PR to address this in the API: https://github.com/BulletTrainHQ/bullet-train-api/pull/56

It might be useful to add some pagination UI, however, in case page sizes constrain the maximum number of features presented.

**Comment by kyle-ssg** [comment]
Ok in that case I’ll close the frontend issue and someone will review the pr, thanks for looking into this! @andrewshawcare
