### ISSUE TITLE
Show description in features list page

### ISSUE THREAD

**Issue by andrewshawcare** [BulletTrainHQ/bullet-train-frontend#34]
### Value proposition
As a Bullet Train user, I want to see descriptions in the feature list so that I can gain more context around what the feature flag represents

### Context
We use the Jira ticket ID as the feature name so we can automate our feature addition/removal flow (webhooks are fired when stories are transitioned into development and transitioned into feature flag removed states).

We use the description to add a link to the ticket itself, so Jira can be our source of truth for all feature flag work. It's a small hassle to click on each feature when we want to gain access to the link.

**Comment by kyle-ssg** [comment]
@andrewshawcare Thanks for the suggestion and great format of bug report! This is now live.
