### ISSUE TITLE
After remove one environment, list with environments are blank

### ISSUE THREAD

**Issue by ksciana** [BulletTrainHQ/bullet-train-frontend#35]
When try remove **Test** env.
![image](https://user-images.githubusercontent.com/1391147/92694425-530fe680-f347-11ea-8498-0e8da232c62c.png)

List with environments are blank.
![image](https://user-images.githubusercontent.com/1391147/92694528-7a66b380-f347-11ea-9099-21c1493544b4.png)

List are filled after re login to site and force site refresh (Ctrl + F5).
![image](https://user-images.githubusercontent.com/1391147/92694878-f6f99200-f347-11ea-8bc3-90babdb3f474.png)

**Comment by kyle-ssg** [comment]
@ksciana thanks for reporting this! This is now fixed, also the redirect logic for remove environment is now improved:

Before: Deleting an environment would send you to the projects page
After: Deleting an environment sends you to the next environment or create environment if none exist
