### ISSUE TITLE
Split Bullet Train web page from feature management panel

### ISSUE THREAD

**Issue by Granjow** [BulletTrainHQ/bullet-train-frontend#6]
At the moment, this repository contains both the official Bulet Train web site and the feature management panel.

I suggest to split the repository into two separate projects, *web page* and *feature panel*, for several reasons.

* Logical separation: The official appearance of the project and management of the features are not influenced by each other.
* Self-hosting only needs the feature management panel but no YouTube video, Pricing, Project Description, …
* Side effects: Introducing a bug in the panel code could bring down the whole web site
* etc. (I think I do not need to elaborate more because it is probably clear anyway)

In the same run, the API keys from [production config files](env/project_prod.js) can be moved to [environment variables](https://12factor.net/config), for example. No commits required anymore when an API key changes. And they are not public anymore …

What is your opinion on that? And is this possible in near future?

**Comment by dabeeeenster** [comment]
Yep that's definitely something we want to do. We are prioritising some other features within the core app at the moment. Happy to accept pull requests or if you're happy to wait we will get to this in the next few weeks.

**Comment by Granjow** [comment]
That’s great! Happy to wait, but if time allows I will send some other pull requests to simplify the split.

Any plans on migrating to TypeScript?

**Comment by kyle-ssg** [comment]
Pretty low likelihood @Granjow, it's quite hard to prioritise that over new features - though updating React / potentially moving to redux and Next is potentially on the radar.

**Comment by kyle-ssg** [comment]
Done. https://github.com/BulletTrainHQ/bullet-train-homepage
